# Generated by Django 3.0.5 on 2020-04-07 18:31

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trainingandtrainers', '0002_ideatraining_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideatraining',
            name='demo',
            field=wagtail.core.fields.StreamField([('doek', wagtail.core.blocks.ChoiceBlock(choices=[('tea', 'Tea'), ('coffee', 'Coffee')]))]),
        ),
    ]
