# Generated by Django 3.0.5 on 2020-04-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingandtrainers', '0003_auto_20200407_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideatraining',
            name='demo',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=250),
        ),
    ]
