# Generated by Django 2.2.12 on 2020-04-09 17:23

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='intro',
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_one_blurp',
            field=wagtail.core.fields.RichTextField(blank=True, default='section_one_blurp'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_one_link',
            field=models.CharField(default='section_one_link', max_length=60),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_one_title',
            field=models.CharField(default='section_one_title', max_length=60),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_three_blurp',
            field=wagtail.core.fields.RichTextField(blank=True, default='section_three_blurp'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_three_link',
            field=models.CharField(default='section_three_link', max_length=60),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_three_title',
            field=models.CharField(default='section_three_title', max_length=60),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_two_blurp',
            field=wagtail.core.fields.RichTextField(blank=True, default='section_two_blurp'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_two_link',
            field=models.CharField(default='section_two_link', max_length=60),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_two_title',
            field=models.CharField(default='section_two_title', max_length=60),
        ),
    ]
