# Generated by Django 2.2.12 on 2020-04-13 11:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import trainingandtrainers.models
import wagtail.contrib.routable_page.models
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
    ]
