# Generated by Django 2.2.12 on 2020-04-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingandtrainers', '0002_blanknewpage_debatecontent_debatecontentcollection_ideaeventindex_ideatrainerindex_ideatrainingindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debatecontent',
            name='level',
            field=models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Advanced')], max_length=250),
        ),
        migrations.AlterField(
            model_name='debatecontent',
            name='targetAudience',
            field=models.CharField(choices=[('primary', 'Primary Education'), ('secondary', 'Secondary Education'), ('tertiary', 'Tertiary Education'), ('adult', 'Adult Education')], max_length=250),
        ),
        migrations.AlterField(
            model_name='pedagogycontent',
            name='level',
            field=models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Advanced')], max_length=250),
        ),
        migrations.AlterField(
            model_name='pedagogycontent',
            name='targetAudience',
            field=models.CharField(choices=[('primary', 'Primary Education'), ('secondary', 'Secondary Education'), ('tertiary', 'Tertiary Education'), ('adult', 'Adult Education')], max_length=250),
        ),
        migrations.AlterField(
            model_name='trainingcontent',
            name='level',
            field=models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Advanced')], max_length=250),
        ),
        migrations.AlterField(
            model_name='trainingcontent',
            name='targetAudience',
            field=models.CharField(choices=[('primary', 'Primary Education'), ('secondary', 'Secondary Education'), ('tertiary', 'Tertiary Education'), ('adult', 'Adult Education')], max_length=250),
        ),
    ]
