# Generated by Django 2.2.12 on 2020-04-12 13:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('trainingandtrainers', '0003_auto_20200411_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaEventIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', wagtail.contrib.routable_page.models.RoutablePageMixin),
        ),
        migrations.CreateModel(
            name='IdeaTrainerIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', wagtail.contrib.routable_page.models.RoutablePageMixin),
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='name',
            new_name='firstName',
        ),
        migrations.RemoveField(
            model_name='allcontent',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='blanknewpage',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='trainingcontent',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='tttevent',
            name='Title',
        ),
        migrations.AddField(
            model_name='trainer',
            name='lastName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainer',
            name='profilePicture',
            field=models.ImageField(upload_to='trainers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
    ]
