# Generated by Django 2.2.12 on 2020-04-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingandtrainers', '0003_auto_20200413_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debatecontent',
            old_name='targetAudience',
            new_name='targetAudience1',
        ),
        migrations.RenameField(
            model_name='pedagogycontent',
            old_name='targetAudience',
            new_name='targetAudience1',
        ),
        migrations.RenameField(
            model_name='trainingcontent',
            old_name='targetAudience',
            new_name='targetAudience1',
        ),
        migrations.AddField(
            model_name='debatecontent',
            name='targetAudience2',
            field=models.CharField(blank=True, choices=[('primary', 'Primary Education'), ('secondary', 'Secondary Education'), ('tertiary', 'Tertiary Education'), ('adult', 'Adult Education')], max_length=250),
        ),
        migrations.AddField(
            model_name='debatecontent',
            name='targetAudience3',
            field=models.CharField(blank=True, choices=[('primary', 'Primary Education'), ('secondary', 'Secondary Education'), ('tertiary', 'Tertiary Education'), ('adult', 'Adult Education')], max_length=250),
        ),
        migrations.AddField(
            model_name='debatecontent',
            name='targetAudience4',
            field=models.CharField(blank=True, choices=[('primary', 'Primary Education'), ('secondary', 'Secondary Education'), ('tertiary', 'Tertiary Education'), ('adult', 'Adult Education')], max_length=250),
        ),
        migrations.AddField(
            model_name='pedagogycontent',
            name='targetAudience2',
            field=models.CharField(blank=True, choices=[('primary', 'Primary Education'), ('secondary', 'Secondary Education'), ('tertiary', 'Tertiary Education'), ('adult', 'Adult Education')], max_length=250),
        ),
        migrations.AddField(
            model_name='pedagogycontent',
            name='targetAudience3',
            field=models.CharField(blank=True, choices=[('primary', 'Primary Education'), ('secondary', 'Secondary Education'), ('tertiary', 'Tertiary Education'), ('adult', 'Adult Education')], max_length=250),
        ),
        migrations.AddField(
            model_name='pedagogycontent',
            name='targetAudience4',
            field=models.CharField(blank=True, choices=[('primary', 'Primary Education'), ('secondary', 'Secondary Education'), ('tertiary', 'Tertiary Education'), ('adult', 'Adult Education')], max_length=250),
        ),
        migrations.AddField(
            model_name='trainingcontent',
            name='targetAudience2',
            field=models.CharField(blank=True, choices=[('primary', 'Primary Education'), ('secondary', 'Secondary Education'), ('tertiary', 'Tertiary Education'), ('adult', 'Adult Education')], max_length=250),
        ),
        migrations.AddField(
            model_name='trainingcontent',
            name='targetAudience3',
            field=models.CharField(blank=True, choices=[('primary', 'Primary Education'), ('secondary', 'Secondary Education'), ('tertiary', 'Tertiary Education'), ('adult', 'Adult Education')], max_length=250),
        ),
        migrations.AddField(
            model_name='trainingcontent',
            name='targetAudience4',
            field=models.CharField(blank=True, choices=[('primary', 'Primary Education'), ('secondary', 'Secondary Education'), ('tertiary', 'Tertiary Education'), ('adult', 'Adult Education')], max_length=250),
        ),
    ]
