# Generated by Django 2.2.12 on 2020-04-13 06:17

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('trainingandtrainers', '0004_auto_20200412_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
                ('section_one_title', models.CharField(default='section_one_title', max_length=60)),
                ('section_one_blurp', wagtail.core.fields.RichTextField(blank=True, default='section_one_blurp')),
                ('section_one_link', models.CharField(default='section_one_link', max_length=60)),
                ('section_two_title', models.CharField(default='section_two_title', max_length=60)),
                ('section_two_blurp', wagtail.core.fields.RichTextField(blank=True, default='section_two_blurp')),
                ('section_two_link', models.CharField(default='section_two_link', max_length=60)),
                ('section_three_title', models.CharField(default='section_three_title', max_length=60)),
                ('section_three_blurp', wagtail.core.fields.RichTextField(blank=True, default='section_three_blurp')),
                ('section_three_link', models.CharField(default='section_three_link', max_length=60)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
