# Generated by Django 2.2.12 on 2020-04-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('trainingandtrainers', '0004_auto_20200413_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tttevent',
            name='typetraining',
            field=models.CharField(default='TTT', max_length=100, verbose_name='type of training'),
        ),
    ]
