# Generated by Django 2.2.12 on 2020-04-13 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingandtrainers', '0005_auto_20200413_1804'),
        ('trainingandtrainers', '0005_auto_20200413_2003'),
    ]

    operations = [
    ]
