# Generated by Django 2.2.12 on 2020-04-13 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('trainingandtrainers', '0006_auto_20200413_0626'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
