# Generated by Django 2.2.12 on 2020-04-13 19:24

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trainingandtrainers', '0006_merge_20200413_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debatecontent',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='pedagogycontent',
            name='summary',
        ),
        migrations.AddField(
            model_name='debatecontent',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedagogycontent',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='shortBio',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
