# Generated by Django 2.2.12 on 2020-04-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('trainingandtrainers', '0006_merge_20200413_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debatecontent',
            name='level',
            field=models.CharField(
                choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')],
                max_length=250),
        ),
        migrations.AlterField(
            model_name='debatecontent',
            name='targetAudience1',
            field=models.CharField(
                choices=[('Primary Education', 'Primary Education'), ('Secondary Education', 'Secondary Education'),
                         ('Tertiary Education', 'Tertiary Education'), ('Adult Education', 'Adult Education')],
                max_length=250),
        ),
        migrations.AlterField(
            model_name='debatecontent',
            name='targetAudience2',
            field=models.CharField(blank=True, choices=[('Primary Education', 'Primary Education'),
                                                        ('Secondary Education', 'Secondary Education'),
                                                        ('Tertiary Education', 'Tertiary Education'),
                                                        ('Adult Education', 'Adult Education')], max_length=250),
        ),
        migrations.AlterField(
            model_name='debatecontent',
            name='targetAudience3',
            field=models.CharField(blank=True, choices=[('Primary Education', 'Primary Education'),
                                                        ('Secondary Education', 'Secondary Education'),
                                                        ('Tertiary Education', 'Tertiary Education'),
                                                        ('Adult Education', 'Adult Education')], max_length=250),
        ),
        migrations.AlterField(
            model_name='debatecontent',
            name='targetAudience4',
            field=models.CharField(blank=True, choices=[('Primary Education', 'Primary Education'),
                                                        ('Secondary Education', 'Secondary Education'),
                                                        ('Tertiary Education', 'Tertiary Education'),
                                                        ('Adult Education', 'Adult Education')], max_length=250),
        ),
        migrations.AlterField(
            model_name='pedagogycontent',
            name='level',
            field=models.CharField(
                choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')],
                max_length=250),
        ),
        migrations.AlterField(
            model_name='pedagogycontent',
            name='targetAudience1',
            field=models.CharField(
                choices=[('Primary Education', 'Primary Education'), ('Secondary Education', 'Secondary Education'),
                         ('Tertiary Education', 'Tertiary Education'), ('Adult Education', 'Adult Education')],
                max_length=250),
        ),
        migrations.AlterField(
            model_name='pedagogycontent',
            name='targetAudience2',
            field=models.CharField(blank=True, choices=[('Primary Education', 'Primary Education'),
                                                        ('Secondary Education', 'Secondary Education'),
                                                        ('Tertiary Education', 'Tertiary Education'),
                                                        ('Adult Education', 'Adult Education')], max_length=250),
        ),
        migrations.AlterField(
            model_name='pedagogycontent',
            name='targetAudience3',
            field=models.CharField(blank=True, choices=[('Primary Education', 'Primary Education'),
                                                        ('Secondary Education', 'Secondary Education'),
                                                        ('Tertiary Education', 'Tertiary Education'),
                                                        ('Adult Education', 'Adult Education')], max_length=250),
        ),
        migrations.AlterField(
            model_name='pedagogycontent',
            name='targetAudience4',
            field=models.CharField(blank=True, choices=[('Primary Education', 'Primary Education'),
                                                        ('Secondary Education', 'Secondary Education'),
                                                        ('Tertiary Education', 'Tertiary Education'),
                                                        ('Adult Education', 'Adult Education')], max_length=250),
        ),
        migrations.AlterField(
            model_name='trainingcontent',
            name='level',
            field=models.CharField(
                choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')],
                max_length=250),
        ),
        migrations.AlterField(
            model_name='trainingcontent',
            name='targetAudience1',
            field=models.CharField(
                choices=[('Primary Education', 'Primary Education'), ('Secondary Education', 'Secondary Education'),
                         ('Tertiary Education', 'Tertiary Education'), ('Adult Education', 'Adult Education')],
                max_length=250),
        ),
        migrations.AlterField(
            model_name='trainingcontent',
            name='targetAudience2',
            field=models.CharField(blank=True, choices=[('Primary Education', 'Primary Education'),
                                                        ('Secondary Education', 'Secondary Education'),
                                                        ('Tertiary Education', 'Tertiary Education'),
                                                        ('Adult Education', 'Adult Education')], max_length=250),
        ),
        migrations.AlterField(
            model_name='trainingcontent',
            name='targetAudience3',
            field=models.CharField(blank=True, choices=[('Primary Education', 'Primary Education'),
                                                        ('Secondary Education', 'Secondary Education'),
                                                        ('Tertiary Education', 'Tertiary Education'),
                                                        ('Adult Education', 'Adult Education')], max_length=250),
        ),
        migrations.AlterField(
            model_name='trainingcontent',
            name='targetAudience4',
            field=models.CharField(blank=True, choices=[('Primary Education', 'Primary Education'),
                                                        ('Secondary Education', 'Secondary Education'),
                                                        ('Tertiary Education', 'Tertiary Education'),
                                                        ('Adult Education', 'Adult Education')], max_length=250),
        ),
    ]
