# Generated by Django 2.2.12 on 2020-04-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingandtrainers', '0007_auto_20200413_2124'),
        ('trainingandtrainers', '0006_merge_20200413_1843'),
    ]

    operations = [
    ]
