# Generated by Django 2.2.12 on 2020-04-13 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('trainingandtrainers', '0007_auto_20200413_1935'),
        ('trainingandtrainers', '0008_merge_20200413_2145'),
    ]

    operations = [
    ]
